@startuml
left to right direction
actor Korisnik
actor Polaznik
actor Organizator
actor Administrator
rectangle "ClayPlay" {

(UC1: Prijava putem OAuth 2.0 servisa)
(UC2: Registracija novog korisnika)
(UC3: Uređivanje profila korisnika)
(UC4: Kreiranje i uređivanje radionice)
(UC5: Pregled radionica)
(UC5: Rezervacija radionica)
(UC6: Plaćanje termina radionice)
(UC7: Odabir i plaćanje članarine)
(UC8: Kupovina proizvoda u online trgovini)
(UC9: Prijava na izložbu)
(UC10: Upravljanje korisnicima i članarinama)

}
together{
actor "OAuth 2.0 servis" as OAuth
actor "PayPal/Kartični servis" as Pay
actor "Google Kalendar" as GCal
}
(UC2: Registracija novog korisnika) <.. (UC1: Prijava putem OAuth 2.0 servisa) : <<extend>>
Korisnik --> (UC2: Registracija novog korisnika)
Korisnik --> (UC8: Kupovina proizvoda u online trgovini)
(UC1: Prijava putem OAuth 2.0 servisa) -- OAuth

(UC8: Kupovina proizvoda u online trgovini) -- Pay
Polaznik --> (UC5: Pregled radionica)
(UC5: Pregled radionica) <.. (UC5: Rezervacija radionica) : <<extend>>
(UC5: Rezervacija radionica) ..> (UC6: Plaćanje termina radionice) : <<include>>
Polaznik --> (UC9: Prijava na izložbu)
(UC6: Plaćanje termina radionice) -- Pay
(UC5: Pregled radionica) -- GCal
Organizator --> (UC4: Kreiranje i uređivanje radionice)
Organizator --> (UC7: Odabir i plaćanje članarine)
Korisnik  --> (UC3: Uređivanje profila korisnika)
(UC7: Odabir i plaćanje članarine) -- Pay


Administrator --> (UC10: Upravljanje korisnicima i članarinama)
@enduml
