


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE TYPE "public"."product_category" AS ENUM (
    'salice',
    'tanjuri',
    'zdjele',
    'skulpture'
);


ALTER TYPE "public"."product_category" OWNER TO "postgres";


COMMENT ON TYPE "public"."product_category" IS 'salice, tanjuri, zdjele, skulpture';


SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."admins" (
    "id" integer NOT NULL,
    "user_id" integer,
    "can_change_prices" boolean,
    "can_approve_users" boolean,
    "can_send_notifications" boolean
);


ALTER TABLE "public"."admins" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."comments" (
    "id" integer NOT NULL,
    "user_id" integer,
    "exhibition_id" integer,
    "content" "text",
    "photo_id" integer,
    "created_at" timestamp without time zone
);


ALTER TABLE "public"."comments" OWNER TO "postgres";


ALTER TABLE "public"."comments" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."comments_id_seq"
    START WITH 3
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."exhibition_products" (
    "id" integer NOT NULL,
    "product_id" integer,
    "exhibition_id" integer
);


ALTER TABLE "public"."exhibition_products" OWNER TO "postgres";


ALTER TABLE "public"."exhibition_products" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."exhibition_products_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."exhibition_registrations" (
    "id" integer NOT NULL,
    "participant_id" integer,
    "exhibition_id" integer,
    "approved" boolean
);


ALTER TABLE "public"."exhibition_registrations" OWNER TO "postgres";


ALTER TABLE "public"."exhibition_registrations" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."exhibition_registrations_id_seq"
    START WITH 4
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."exhibitions" (
    "id" integer NOT NULL,
    "organizer_id" integer,
    "title" "text",
    "location" "text",
    "date_time" timestamp without time zone,
    "description" "text"
);


ALTER TABLE "public"."exhibitions" OWNER TO "postgres";


ALTER TABLE "public"."exhibitions" ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME "public"."exhibitions_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."membership_plans" (
    "id" integer NOT NULL,
    "name" "text",
    "price" numeric,
    "duration_months" integer,
    "description" "text"
);


ALTER TABLE "public"."membership_plans" OWNER TO "postgres";


COMMENT ON COLUMN "public"."membership_plans"."description" IS 'Membership plan''s short description';



CREATE TABLE IF NOT EXISTS "public"."membership_transactions" (
    "id" integer NOT NULL,
    "organizer_id" integer,
    "transaction_id" integer,
    "membership_plan_id" integer NOT NULL
);


ALTER TABLE "public"."membership_transactions" OWNER TO "postgres";


COMMENT ON COLUMN "public"."membership_transactions"."membership_plan_id" IS 'Plan of paid membership - membership_plan foreign key';



ALTER TABLE "public"."membership_transactions" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."membership_transactions_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."notification_subscriptions" (
    "id" integer NOT NULL,
    "user_id" integer,
    "type" "text",
    "started_at" timestamp without time zone
);


ALTER TABLE "public"."notification_subscriptions" OWNER TO "postgres";


ALTER TABLE "public"."notification_subscriptions" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."notification_subscriptions_id_seq"
    START WITH 4
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."notifications" (
    "id" integer NOT NULL,
    "body" "text",
    "type" "text",
    "title" "text",
    "subtitle" "text",
    "subject" "text",
    "created_at" timestamp without time zone
);


ALTER TABLE "public"."notifications" OWNER TO "postgres";


ALTER TABLE "public"."notifications" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."notifications_id_seq"
    START WITH 4
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."orders" (
    "id" integer NOT NULL,
    "participant_id" integer,
    "order_time" timestamp without time zone,
    "transaction_id" integer
);


ALTER TABLE "public"."orders" OWNER TO "postgres";


ALTER TABLE "public"."orders" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."orders_id_seq"
    START WITH 3
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."organizer_photos" (
    "id" integer NOT NULL,
    "photo_id" integer,
    "organizer_id" integer
);


ALTER TABLE "public"."organizer_photos" OWNER TO "postgres";


ALTER TABLE "public"."organizer_photos" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."organizer_photos_id_seq"
    START WITH 8
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."organizers" (
    "id" integer NOT NULL,
    "user_id" integer,
    "membership_plan_id" integer,
    "membership_expiry_date" "date",
    "profile_name" "text",
    "logo_photo_id" integer,
    "banner_photo_id" integer,
    "description" "text",
    "approved_by_admin" boolean
);


ALTER TABLE "public"."organizers" OWNER TO "postgres";


ALTER TABLE "public"."organizers" ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME "public"."organizers_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."participants" (
    "id" integer NOT NULL,
    "user_id" integer
);


ALTER TABLE "public"."participants" OWNER TO "postgres";


ALTER TABLE "public"."participants" ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME "public"."participants_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."photos" (
    "id" integer NOT NULL,
    "url" "text",
    "description" "text"
);


ALTER TABLE "public"."photos" OWNER TO "postgres";


ALTER TABLE "public"."photos" ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME "public"."photos_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."product_reviews" (
    "id" integer NOT NULL,
    "participant_id" integer,
    "product_id" integer,
    "rating" integer,
    "text" "text",
    "created_at" timestamp without time zone
);


ALTER TABLE "public"."product_reviews" OWNER TO "postgres";


ALTER TABLE "public"."product_reviews" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."product_reviews_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."products" (
    "id" integer NOT NULL,
    "name" "text",
    "description" "text",
    "price" numeric,
    "photo_id" integer,
    "quantity_left" integer NOT NULL,
    "exhibition_id" integer,
    "seller_id" integer NOT NULL,
    "category" "public"."product_category",
    "sold_at_least_once" boolean
);


ALTER TABLE "public"."products" OWNER TO "postgres";


ALTER TABLE "public"."products" ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME "public"."products_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."products_orders" (
    "id" integer NOT NULL,
    "product_id" integer,
    "order_id" integer,
    "quantity" integer
);


ALTER TABLE "public"."products_orders" OWNER TO "postgres";


ALTER TABLE "public"."products_orders" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."products_orders_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."read_notifications" (
    "id" integer NOT NULL,
    "user_id" integer,
    "notification_id" integer,
    "marked_as_read" boolean
);


ALTER TABLE "public"."read_notifications" OWNER TO "postgres";


ALTER TABLE "public"."read_notifications" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."read_notifications_id_seq"
    START WITH 3
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."transactions" (
    "id" integer NOT NULL,
    "amount" numeric,
    "method" "text",
    "date_time" timestamp without time zone,
    "paypal_order_id" "text"
);


ALTER TABLE "public"."transactions" OWNER TO "postgres";


ALTER TABLE "public"."transactions" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."transactions_id_seq"
    START WITH 3
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."users" (
    "id" integer NOT NULL,
    "first_name" "text",
    "last_name" "text",
    "username" "text",
    "address" "text",
    "mail" "text",
    "phone" "text",
    "profile_photo_id" integer,
    "auth_id" "uuid"
);


ALTER TABLE "public"."users" OWNER TO "postgres";


ALTER TABLE "public"."users" ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME "public"."users_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."workshop_reservations" (
    "id" integer NOT NULL,
    "workshop_id" integer,
    "participant_id" integer,
    "transaction_id" integer
);


ALTER TABLE "public"."workshop_reservations" OWNER TO "postgres";


ALTER TABLE "public"."workshop_reservations" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."workshop_reservations_id_seq"
    START WITH 3
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."workshops" (
    "id" integer NOT NULL,
    "organizer_id" integer,
    "title" "text",
    "duration" time without time zone,
    "date_time" timestamp without time zone,
    "location" "text",
    "capacity" integer,
    "price" numeric,
    "description" "text"
);


ALTER TABLE "public"."workshops" OWNER TO "postgres";


ALTER TABLE "public"."workshops" ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME "public"."workshops_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."admins"
    ADD CONSTRAINT "admins_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."comments"
    ADD CONSTRAINT "comments_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."exhibition_products"
    ADD CONSTRAINT "exhibition_products_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."exhibition_registrations"
    ADD CONSTRAINT "exhibition_registrations_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."exhibitions"
    ADD CONSTRAINT "exhibitions_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."membership_plans"
    ADD CONSTRAINT "membership_plans_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."membership_transactions"
    ADD CONSTRAINT "membership_transactions_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."notification_subscriptions"
    ADD CONSTRAINT "notification_subscriptions_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."notifications"
    ADD CONSTRAINT "notifications_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."orders"
    ADD CONSTRAINT "orders_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."organizer_photos"
    ADD CONSTRAINT "organizer_photos_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."organizers"
    ADD CONSTRAINT "organizers_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."participants"
    ADD CONSTRAINT "participants_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."photos"
    ADD CONSTRAINT "photos_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."product_reviews"
    ADD CONSTRAINT "product_reviews_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."products_orders"
    ADD CONSTRAINT "products_orders_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."products"
    ADD CONSTRAINT "products_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."read_notifications"
    ADD CONSTRAINT "read_notifications_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."transactions"
    ADD CONSTRAINT "transactions_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."users"
    ADD CONSTRAINT "users_auth_id_key" UNIQUE ("auth_id");



ALTER TABLE ONLY "public"."users"
    ADD CONSTRAINT "users_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."workshop_reservations"
    ADD CONSTRAINT "workshop_reservations_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."workshops"
    ADD CONSTRAINT "workshops_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."admins"
    ADD CONSTRAINT "admins_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."comments"
    ADD CONSTRAINT "comments_exhibition_id_fkey" FOREIGN KEY ("exhibition_id") REFERENCES "public"."exhibitions"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."comments"
    ADD CONSTRAINT "comments_photo_id_fkey" FOREIGN KEY ("photo_id") REFERENCES "public"."photos"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."comments"
    ADD CONSTRAINT "comments_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."exhibition_products"
    ADD CONSTRAINT "exhibition_products_exhibition_id_fkey" FOREIGN KEY ("exhibition_id") REFERENCES "public"."exhibitions"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."exhibition_products"
    ADD CONSTRAINT "exhibition_products_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "public"."products"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."exhibition_registrations"
    ADD CONSTRAINT "exhibition_registrations_exhibition_id_fkey" FOREIGN KEY ("exhibition_id") REFERENCES "public"."exhibitions"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."exhibition_registrations"
    ADD CONSTRAINT "exhibition_registrations_participant_id_fkey" FOREIGN KEY ("participant_id") REFERENCES "public"."participants"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."exhibitions"
    ADD CONSTRAINT "exhibitions_organizer_id_fkey" FOREIGN KEY ("organizer_id") REFERENCES "public"."organizers"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."membership_transactions"
    ADD CONSTRAINT "membership_transactions_membership_plan_id_fkey" FOREIGN KEY ("membership_plan_id") REFERENCES "public"."membership_plans"("id");



ALTER TABLE ONLY "public"."membership_transactions"
    ADD CONSTRAINT "membership_transactions_organizer_id_fkey" FOREIGN KEY ("organizer_id") REFERENCES "public"."organizers"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."membership_transactions"
    ADD CONSTRAINT "membership_transactions_transaction_id_fkey" FOREIGN KEY ("transaction_id") REFERENCES "public"."transactions"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."notification_subscriptions"
    ADD CONSTRAINT "notification_subscriptions_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."orders"
    ADD CONSTRAINT "orders_participant_id_fkey" FOREIGN KEY ("participant_id") REFERENCES "public"."participants"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."orders"
    ADD CONSTRAINT "orders_transaction_id_fkey" FOREIGN KEY ("transaction_id") REFERENCES "public"."transactions"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."organizer_photos"
    ADD CONSTRAINT "organizer_photos_organizer_fkey" FOREIGN KEY ("organizer_id") REFERENCES "public"."organizers"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."organizer_photos"
    ADD CONSTRAINT "organizer_photos_photo_id_fkey" FOREIGN KEY ("photo_id") REFERENCES "public"."photos"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."organizers"
    ADD CONSTRAINT "organizers_banner_photo_id_fkey" FOREIGN KEY ("banner_photo_id") REFERENCES "public"."photos"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."organizers"
    ADD CONSTRAINT "organizers_logo_photo_id_fkey" FOREIGN KEY ("logo_photo_id") REFERENCES "public"."photos"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."organizers"
    ADD CONSTRAINT "organizers_membership_plan_id_fkey" FOREIGN KEY ("membership_plan_id") REFERENCES "public"."membership_plans"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."organizers"
    ADD CONSTRAINT "organizers_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."participants"
    ADD CONSTRAINT "participants_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."product_reviews"
    ADD CONSTRAINT "product_reviews_participant_id_fkey" FOREIGN KEY ("participant_id") REFERENCES "public"."participants"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."product_reviews"
    ADD CONSTRAINT "product_reviews_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "public"."products"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."products"
    ADD CONSTRAINT "products_exhibition_id_fkey" FOREIGN KEY ("exhibition_id") REFERENCES "public"."exhibitions"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."products_orders"
    ADD CONSTRAINT "products_orders_order_id_fkey" FOREIGN KEY ("order_id") REFERENCES "public"."orders"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."products_orders"
    ADD CONSTRAINT "products_orders_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "public"."products"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."products"
    ADD CONSTRAINT "products_photo_id_fkey" FOREIGN KEY ("photo_id") REFERENCES "public"."photos"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."products"
    ADD CONSTRAINT "products_seller_id_fkey" FOREIGN KEY ("seller_id") REFERENCES "public"."organizers"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."read_notifications"
    ADD CONSTRAINT "read_notifications_notification_id_fkey" FOREIGN KEY ("notification_id") REFERENCES "public"."notifications"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."read_notifications"
    ADD CONSTRAINT "read_notifications_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."users"
    ADD CONSTRAINT "users_profile_photo_id_fkey" FOREIGN KEY ("profile_photo_id") REFERENCES "public"."photos"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."workshop_reservations"
    ADD CONSTRAINT "workshop_reservations_participant_id_fkey" FOREIGN KEY ("participant_id") REFERENCES "public"."participants"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."workshop_reservations"
    ADD CONSTRAINT "workshop_reservations_transaction_id_fkey" FOREIGN KEY ("transaction_id") REFERENCES "public"."transactions"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."workshop_reservations"
    ADD CONSTRAINT "workshop_reservations_workshop_id_fkey" FOREIGN KEY ("workshop_id") REFERENCES "public"."workshops"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."workshops"
    ADD CONSTRAINT "workshops_organizer_id_fkey" FOREIGN KEY ("organizer_id") REFERENCES "public"."organizers"("id") ON DELETE CASCADE;





ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";








































































































































































GRANT ALL ON TABLE "public"."admins" TO "anon";
GRANT ALL ON TABLE "public"."admins" TO "authenticated";
GRANT ALL ON TABLE "public"."admins" TO "service_role";



GRANT ALL ON TABLE "public"."comments" TO "anon";
GRANT ALL ON TABLE "public"."comments" TO "authenticated";
GRANT ALL ON TABLE "public"."comments" TO "service_role";



GRANT ALL ON SEQUENCE "public"."comments_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."comments_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."comments_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."exhibition_products" TO "anon";
GRANT ALL ON TABLE "public"."exhibition_products" TO "authenticated";
GRANT ALL ON TABLE "public"."exhibition_products" TO "service_role";



GRANT ALL ON SEQUENCE "public"."exhibition_products_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."exhibition_products_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."exhibition_products_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."exhibition_registrations" TO "anon";
GRANT ALL ON TABLE "public"."exhibition_registrations" TO "authenticated";
GRANT ALL ON TABLE "public"."exhibition_registrations" TO "service_role";



GRANT ALL ON SEQUENCE "public"."exhibition_registrations_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."exhibition_registrations_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."exhibition_registrations_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."exhibitions" TO "anon";
GRANT ALL ON TABLE "public"."exhibitions" TO "authenticated";
GRANT ALL ON TABLE "public"."exhibitions" TO "service_role";



GRANT ALL ON SEQUENCE "public"."exhibitions_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."exhibitions_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."exhibitions_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."membership_plans" TO "anon";
GRANT ALL ON TABLE "public"."membership_plans" TO "authenticated";
GRANT ALL ON TABLE "public"."membership_plans" TO "service_role";



GRANT ALL ON TABLE "public"."membership_transactions" TO "anon";
GRANT ALL ON TABLE "public"."membership_transactions" TO "authenticated";
GRANT ALL ON TABLE "public"."membership_transactions" TO "service_role";



GRANT ALL ON SEQUENCE "public"."membership_transactions_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."membership_transactions_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."membership_transactions_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."notification_subscriptions" TO "anon";
GRANT ALL ON TABLE "public"."notification_subscriptions" TO "authenticated";
GRANT ALL ON TABLE "public"."notification_subscriptions" TO "service_role";



GRANT ALL ON SEQUENCE "public"."notification_subscriptions_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."notification_subscriptions_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."notification_subscriptions_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."notifications" TO "anon";
GRANT ALL ON TABLE "public"."notifications" TO "authenticated";
GRANT ALL ON TABLE "public"."notifications" TO "service_role";



GRANT ALL ON SEQUENCE "public"."notifications_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."notifications_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."notifications_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."orders" TO "anon";
GRANT ALL ON TABLE "public"."orders" TO "authenticated";
GRANT ALL ON TABLE "public"."orders" TO "service_role";



GRANT ALL ON SEQUENCE "public"."orders_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."orders_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."orders_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."organizer_photos" TO "anon";
GRANT ALL ON TABLE "public"."organizer_photos" TO "authenticated";
GRANT ALL ON TABLE "public"."organizer_photos" TO "service_role";



GRANT ALL ON SEQUENCE "public"."organizer_photos_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."organizer_photos_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."organizer_photos_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."organizers" TO "anon";
GRANT ALL ON TABLE "public"."organizers" TO "authenticated";
GRANT ALL ON TABLE "public"."organizers" TO "service_role";



GRANT ALL ON SEQUENCE "public"."organizers_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."organizers_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."organizers_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."participants" TO "anon";
GRANT ALL ON TABLE "public"."participants" TO "authenticated";
GRANT ALL ON TABLE "public"."participants" TO "service_role";



GRANT ALL ON SEQUENCE "public"."participants_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."participants_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."participants_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."photos" TO "anon";
GRANT ALL ON TABLE "public"."photos" TO "authenticated";
GRANT ALL ON TABLE "public"."photos" TO "service_role";



GRANT ALL ON SEQUENCE "public"."photos_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."photos_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."photos_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."product_reviews" TO "anon";
GRANT ALL ON TABLE "public"."product_reviews" TO "authenticated";
GRANT ALL ON TABLE "public"."product_reviews" TO "service_role";



GRANT ALL ON SEQUENCE "public"."product_reviews_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."product_reviews_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."product_reviews_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."products" TO "anon";
GRANT ALL ON TABLE "public"."products" TO "authenticated";
GRANT ALL ON TABLE "public"."products" TO "service_role";



GRANT ALL ON SEQUENCE "public"."products_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."products_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."products_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."products_orders" TO "anon";
GRANT ALL ON TABLE "public"."products_orders" TO "authenticated";
GRANT ALL ON TABLE "public"."products_orders" TO "service_role";



GRANT ALL ON SEQUENCE "public"."products_orders_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."products_orders_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."products_orders_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."read_notifications" TO "anon";
GRANT ALL ON TABLE "public"."read_notifications" TO "authenticated";
GRANT ALL ON TABLE "public"."read_notifications" TO "service_role";



GRANT ALL ON SEQUENCE "public"."read_notifications_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."read_notifications_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."read_notifications_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."transactions" TO "anon";
GRANT ALL ON TABLE "public"."transactions" TO "authenticated";
GRANT ALL ON TABLE "public"."transactions" TO "service_role";



GRANT ALL ON SEQUENCE "public"."transactions_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."transactions_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."transactions_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."users" TO "anon";
GRANT ALL ON TABLE "public"."users" TO "authenticated";
GRANT ALL ON TABLE "public"."users" TO "service_role";



GRANT ALL ON SEQUENCE "public"."users_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."users_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."users_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."workshop_reservations" TO "anon";
GRANT ALL ON TABLE "public"."workshop_reservations" TO "authenticated";
GRANT ALL ON TABLE "public"."workshop_reservations" TO "service_role";



GRANT ALL ON SEQUENCE "public"."workshop_reservations_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."workshop_reservations_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."workshop_reservations_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."workshops" TO "anon";
GRANT ALL ON TABLE "public"."workshops" TO "authenticated";
GRANT ALL ON TABLE "public"."workshops" TO "service_role";



GRANT ALL ON SEQUENCE "public"."workshops_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."workshops_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."workshops_id_seq" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";































drop extension if exists "pg_net";


  create policy "policy 1io9m69_0"
  on "storage"."objects"
  as permissive
  for select
  to public
using ((auth.uid() IS NOT NULL));



  create policy "policy 1io9m69_1"
  on "storage"."objects"
  as permissive
  for insert
  to public
with check ((auth.uid() IS NOT NULL));



  create policy "policy 1io9m69_2"
  on "storage"."objects"
  as permissive
  for update
  to public
using ((auth.uid() IS NOT NULL));



  create policy "policy 1io9m69_3"
  on "storage"."objects"
  as permissive
  for delete
  to public
using ((auth.uid() IS NOT NULL));



